FROM flink:1.18-java11
USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    pip3 install apache-flink==1.18.1 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/pyflink-jobs
